export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_ENTIRE_CART = 'CLEAR_ENTIRE_CART';
export const ADD_ITEM_QUANTITY = 'ADD_ITEM_QUANTITY';
export const SUBTRACT_ITEM_QUANTITY = 'SUBTRACT_ITEM_QUANTITY';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SERVICES = 'GET_SERVICES';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const GET_ERROR = 'GET_ERROR';
